// Service Worker for Hoshii PWA
// Note: next-pwa generates the actual service worker automatically
// This file serves as documentation of the service worker strategy

// The actual service worker is generated by next-pwa and includes:
// - Precaching of static assets
// - Runtime caching strategies
// - Offline fallback
// - Background sync

// Configuration is in next.config.js:
// - dest: 'public' - Output directory
// - register: true - Auto-register service worker
// - skipWaiting: true - Activate immediately
// - disable: dev mode - Only in production

// Generated files:
// - public/sw.js - Main service worker
// - public/workbox-*.js - Workbox runtime
// - public/worker-*.js - Background sync worker

export {};


